version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file: ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  pgdata:
